import type { Metadata } from 'next'
import './globals.css'
import '@krds-ui/core/dist/style.css'
import AuthListener from '@/utils/authListener'
import { Toaster } from 'sonner'
import QueryProvider from '@/components/QueryProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <html lang="en">
        <QueryProvider>
          <AuthListener />
          <body className={`antialiased`}>{children}</body>
        </QueryProvider>
      </html>
      <Toaster richColors position="top-right" />
    </>
  )
}
